FROM openjdk:8u181-jdk-stretch

MAINTAINER Numery Zaber "support@softwaredeveloper.com"

EXPOSE 8888

COPY maven/spring-cloud-config-server-0.0.1-SNAPSHOT.jar spring-cloud-config-server.jar 

CMD ["java","-jar","spring-cloud-config-server.jar"]