FROM openjdk:8u181-jdk-stretch

MAINTAINER Numery Zaber "support@softwaredeveloper.com"

EXPOSE 8080

COPY maven/customer-service-mysql-0.0.1-SNAPSHOT.jar customer-service-mysql.jar 

CMD ["java","-jar","customer-service-mysql.jar"]