FROM openjdk:8u181-jdk-stretch

MAINTAINER Numery Zaber "support@softwaredeveloper.com"

EXPOSE 8761

COPY maven/netflix-eureka-naming-server-0.0.1-SNAPSHOT.jar netflix-eureka-naming-server.jar 

CMD ["java","-jar","netflix-eureka-naming-server.jar"]