FROM openjdk:8u181-jdk-stretch

MAINTAINER Numery Zaber "support@softwaredeveloper.com"

EXPOSE 8100

COPY maven/customer-account-mysql-0.0.1-SNAPSHOT.jar customer-account-mysql.jar 

CMD ["java","-jar","customer-account-mysql.jar"]